### ISSUE TITLE
[FEATURE_REQUEST] Dark mode

### ISSUE THREAD

**Issue by urmilshroff** [urmilshroff/muze#5]
**Describe your idea**
We need a dark mode🌚

**Comment by michaeldadzie** [comment]
@urmilshroff can i work on this issue?

**Comment by urmilshroff** [comment]
> @urmilshroff can i work on this issue?
> 

@michaeldadzie Sure, go ahead. You can create a new `ThemeData` variable for dark mode in `lib/utils/app_theme.dart` and add a toggle to choose themes somewhere in the app. Also make sure you save the users settings with Hive.

**Comment by urmilshroff** [comment]
Closing this issue as dark mode was implemented in PR #10 by @michaeldadzie. Feel free to reopen this issue if you have better suggestions!
